frameworkVersion: '>=1.0.0 <2.0.0'

service: dummy-test

functions:
  main:
    handler: simple.main
    events:
      - http:
          path: Web
          method: Endpoint
          cors: true